name: Build MBMicroDS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: devkitpro/devkitarm:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install missing packages
      run: |
        dkp-pacman -Syu --noconfirm
        dkp-pacman -S calico --noconfirm

    - name: Build
      run: |
        cd MBMicroDS
        make clean
        make

    - name: Upload .nds
      uses: actions/upload-artifact@v4
      with:
        name: MBMicroDS
        path: MBMicroDS/MBMicroDS.nds
