name: Build MBMicroDS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: devkitpro/devkitarm:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fix devkitPro packages
      run: |
        pacman-key --init
        pacman-key --populate
        pacman -Syu --noconfirm
        pacman -S calico libnds ndstool --noconfirm

    - name: Build
      run: |
        cd MBMicroDS
        make clean
        make

    - name: Upload .nds
      uses: actions/upload-artifact@v4
      with:
        name: MBMicroDS
        path: MBMicroDS/MBMicroDS.nds
